### ISSUE TITLE
AB32VG1 SDK v 1.1.0 

### ISSUE THREAD

**Issue by Eltopinovatif** [RT-Thread-Studio/sdk-index#435]
RT-thread setting: enable ADC and on chip flash, when compiled shows an error. can anyone help me with this problem

**Comment by Eltopinovatif** [comment]
internal flash config, if it compiles an error appears: no file "fal.h" was found in the directory. please help with the solution

**Comment by Eltopinovatif** [comment]
ADC configuration, if it compiles the error appears:

03:58:42 **** Build of configuration Debug for project ADC ****
make -j8 all2 
riscv64-unknown-elf-gcc "../rt-thread/src/clock.c"
riscv64-unknown-elf-gcc "../rt-thread/src/components.c"
riscv64-unknown-elf-gcc "../rt-thread/src/device.c"
riscv64-unknown-elf-gcc "../rt-thread/src/idle.c"
riscv64-unknown-elf-gcc "../rt-thread/src/ipc.c"
riscv64-unknown-elf-gcc "../rt-thread/src/irq.c"
riscv64-unknown-elf-gcc "../rt-thread/src/kservice.c"
riscv64-unknown-elf-gcc "../rt-thread/src/mem.c"
riscv64-unknown-elf-gcc "../rt-thread/src/memheap.c"
riscv64-unknown-elf-gcc "../rt-thread/src/mempool.c"
riscv64-unknown-elf-gcc "../rt-thread/src/object.c"
riscv64-unknown-elf-gcc "../rt-thread/src/scheduler.c"
riscv64-unknown-elf-gcc "../rt-thread/src/thread.c"
riscv64-unknown-elf-gcc "../rt-thread/src/timer.c"
riscv64-unknown-elf-gcc "../rt-thread/components/libc/compilers/newlib/syscalls.c"
riscv64-unknown-elf-gcc "../rt-thread/components/libc/compilers/common/stdlib.c"
riscv64-unknown-elf-gcc "../rt-thread/components/libc/compilers/common/time.c"
riscv64-unknown-elf-gcc "../rt-thread/components/finsh/cmd.c"
riscv64-unknown-elf-gcc "../rt-thread/components/finsh/msh.c"
riscv64-unknown-elf-gcc "../rt-thread/components/finsh/shell.c"
riscv64-unknown-elf-gcc "../rt-thread/components/drivers/serial/serial.c"
riscv64-unknown-elf-gcc "../rt-thread/components/drivers/misc/adc.c"
riscv64-unknown-elf-gcc "../rt-thread/components/drivers/misc/pin.c"
riscv64-unknown-elf-gcc "../rt-thread/components/drivers/ipc/completion.c"
riscv64-unknown-elf-gcc "../rt-thread/components/drivers/ipc/dataqueue.c"
riscv64-unknown-elf-gcc "../rt-thread/components/drivers/ipc/pipe.c"
riscv64-unknown-elf-gcc "../rt-thread/components/drivers/ipc/ringblk_buf.c"
riscv64-unknown-elf-gcc "../rt-thread/components/drivers/ipc/ringbuffer.c"
riscv64-unknown-elf-gcc "../rt-thread/components/drivers/ipc/waitqueue.c"
riscv64-unknown-elf-gcc "../rt-thread/components/drivers/ipc/workqueue.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/porting/npl/rtthread/src/ble_platform.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/porting/npl/rtthread/src/hci_rtthread.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/porting/npl/rtthread/src/nimble_port_rtthread.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/porting/npl/rtthread/src/npl_os_rtthread.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/porting/npl/rtthread/src/npl_shell.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/porting/nimble/src/endian.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/porting/nimble/src/mem.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/porting/nimble/src/nimble_port.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/porting/nimble/src/os_mbuf.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/porting/nimble/src/os_mempool.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/porting/nimble/src/os_msys_init.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/util/src/addr.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/store/ram/src/ble_store_ram.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_att.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_att_clt.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_att_cmd.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_att_svr.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_eddystone.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_gap.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_gattc.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_gatts.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_gatts_lcl.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_adv.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_atomic.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_cfg.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_conn.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_flow.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_hci.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_hci_cmd.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_hci_evt.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_hci_util.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_id.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_log.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_mbuf.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_misc.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_mqueue.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_periodic_sync.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_pvcy.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_shutdown.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_startup.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_hs_stop.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_ibeacon.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_l2cap.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_l2cap_coc.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_l2cap_sig.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_l2cap_sig_cmd.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_monitor.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_sm.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_sm_alg.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_sm_cmd.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_sm_lgcy.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_sm_sc.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_store.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_store_util.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/src/ble_uuid.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/services/tps/src/ble_svc_tps.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/services/lls/src/ble_svc_lls.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/services/ipss/src/ble_svc_ipss.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/services/ias/src/ble_svc_ias.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/services/gatt/src/ble_svc_gatt.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/services/gap/src/ble_svc_gap.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/services/dis/src/ble_svc_dis.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/services/bas/src/ble_svc_bas.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/nimble/host/services/ans/src/ble_svc_ans.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/ext/tinycrypt/src/aes_decrypt.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/ext/tinycrypt/src/aes_encrypt.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/ext/tinycrypt/src/cbc_mode.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/ext/tinycrypt/src/ccm_mode.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/ext/tinycrypt/src/cmac_mode.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/ext/tinycrypt/src/ctr_mode.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/ext/tinycrypt/src/ctr_prng.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/ext/tinycrypt/src/ecc.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/ext/tinycrypt/src/ecc_dh.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/ext/tinycrypt/src/ecc_dsa.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/ext/tinycrypt/src/ecc_platform_specific.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/ext/tinycrypt/src/hmac.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/ext/tinycrypt/src/hmac_prng.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/ext/tinycrypt/src/sha256.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/ext/tinycrypt/src/utils.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/apps/blehr/src/blehr.c"
riscv64-unknown-elf-gcc "../packages/bluetrum_sdk-latest/bluetrum_nimble/apps/blehr/src/gatt_svr.c"
riscv64-unknown-elf-gcc "../libraries/hal_libraries/bmsis/source/startup.S"
riscv64-unknown-elf-gcc "../libraries/hal_libraries/bmsis/source/system_ab32vgx.c"
riscv64-unknown-elf-gcc "../libraries/hal_libraries/ab32vg1_hal/source/ab32vg1_hal.c"
riscv64-unknown-elf-gcc "../libraries/hal_libraries/ab32vg1_hal/source/ab32vg1_hal_dac.c"
riscv64-unknown-elf-gcc "../libraries/hal_libraries/ab32vg1_hal/source/ab32vg1_hal_gpio.c"
riscv64-unknown-elf-gcc "../libraries/hal_libraries/ab32vg1_hal/source/ab32vg1_hal_rcu.c"
riscv64-unknown-elf-gcc "../libraries/hal_libraries/ab32vg1_hal/source/ab32vg1_hal_sd.c"
riscv64-unknown-elf-gcc "../libraries/hal_libraries/ab32vg1_hal/source/ab32vg1_hal_uart.c"
riscv64-unknown-elf-gcc "../libraries/hal_drivers/drv_adc.c"
riscv64-unknown-elf-gcc "../libraries/hal_drivers/drv_common.c"
riscv64-unknown-elf-gcc "../libraries/hal_drivers/drv_gpio.c"
riscv64-unknown-elf-gcc "../libraries/hal_drivers/drv_usart.c"
riscv64-unknown-elf-gcc "../libcpu/cpu/context_gcc.S"
riscv64-unknown-elf-gcc "../libcpu/cpu/cpuport.c"
riscv64-unknown-elf-gcc "../libcpu/cpu/interrupt.c"
riscv64-unknown-elf-gcc "../board/ab32vg1_hal_msp.c"
riscv64-unknown-elf-gcc "../board/board.c"
riscv64-unknown-elf-gcc "../applications/blehr_app.c"
riscv64-unknown-elf-gcc "../applications/main.c"
riscv64-unknown-elf-gcc "../applications/mnt.c"
linking...
d:/rt-threadstudio/repo/extract/toolchain_support_packages/risc-v/risc-v-gcc/10.1.0/bin/../lib/gcc/riscv64-unknown-elf/10.1.0/../../../../riscv64-unknown-elf/bin/ld.exe: address 0x57b6c of rtthread.elf section `.ram1' is not within region `ram1'
d:/rt-threadstudio/repo/extract/toolchain_support_packages/risc-v/risc-v-gcc/10.1.0/bin/../lib/gcc/riscv64-unknown-elf/10.1.0/../../../../riscv64-unknown-elf/bin/ld.exe: address 0x57b6c of rtthread.elf section `.ram1' is not within region `ram1'
collect2.exe: error: ld returned 1 exit status
make: *** [makefile:76: rtthread.elf] Error 1
"make -j8 all2" terminated with exit code 2. Build might be incomplete.

03:58:57 Build Failed. 3 errors, 0 warnings. (took 14s.553ms)

**Comment by eclipsesw** [comment]
谢谢，反馈，该问题已经转达中科蓝讯官方了
